### ISSUE TITLE
Upgrade reactive library to 6.0 to support async subscribers

### ISSUE THREAD

**Issue by mmsommer** [agnauck/XmppDotNet#29]
System.Reactive 5.0 does not yet support asynchronous subscription. Simply upgrading it to 6.0 would fix it.

**Comment by agnauck** [comment]
updating System.Reactive is on top of my TODO list.
According to my research the update should be safe and simple. But because its a core part of the library I need to make many automated and manual tests before I can commit this to master.

Just curious if you have been running some tests already with System.Reactive 6

**Comment by mmsommer** [comment]
@agnauck no, sorry. I have not any test running with Reactive 6. I only found out that I needed for my system an asynchronous observer pattern, which I thought was only supported from 6 onwards. But actually found out that it was already supported from 5. Therefor I retracted my comment as I was already able to use it as such.
